# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 294d56945ab9e52b004de764be01f61043c4780ed6ce25e4f6a196c0af06665e071663a508a4c8655665e0c4c442228361d5bdb109a072c50c64b3a15b437059

test:
  secret_key_base: 85764836321467d714d10e748cd8487615c6ea4abee61182c44208459cb9bd20946c9bfaacd05155c9178311ceffc6ae95d5df36175968ac1a7711d8f46d3e1e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
